version: '3'
services:
  guvi:
    # Use the image built by the Dockerfile
    build:
      context: .
      dockerfile: Dockerfile
        # Container name
    container_name: guvi-app-container
    # Map the container's port 80 to the host's port 3000 (or any port you prefer)
    ports:
      - "80:80"
    networks:
      - my-network

  express-server:
    build:
      context: ./express-server
    ports:
      - "3001:3001"
    networks:
      - my-network

  node-exporter:
    image: prom/node-exporter
    ports:
      - "9100:9100"
    networks:
      - my-network

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - my-network
    depends_on:
      - express-server
      - node-exporter

  grafana:
    image: grafana/grafana
    ports:
      - "3002:3000"
    networks:
      - my-network
    depends_on:
      - prometheus
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin # Default password, should be changed in production
      - GF_SMTP_ENABLED=true
      - GF_SMTP_HOST=smtp.gmail.com:587 # Replace with your SMTP server
      - GF_SMTP_USER=manoharsankar93@gmail.com # Replace with your email username
      - GF_SMTP_PASSWORD=oach zjyu iymt svmt     # Replace with your email password
      - GF_SMTP_FROM_ADDRESS=alert@example.com # The email address from which alerts will be sent
      - GF_SMTP_FROM_NAME=Grafana Alerts
      - GF_SMTP_SKIP_VERIFY=true  # Optional, skip SSL verification if using self-signed certs
    volumes:
      - grafana-storage:/var/lib/grafana
    restart: always

volumes:
  grafana-storage:

networks:
  my-network:
    driver: bridge

